# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://AaronCHH.github.io/nbdev5/"

git_url = "https://github.com/AaronCHH/nbdev5/tree/main/"

def custom_doc_links(name): return None
